package com.estore.entity;

// default package
// Generated Aug 23, 2020 8:16:43 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DanhMucSanPham generated by hbm2java
 */
@Entity
@Table(name = "AnhBia")
public class AnhBia implements Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	Integer maAB;
	String imgUrl;
	
	public Integer getMaAB() {
		return maAB;
	}
	public void setMaAB(Integer maAB) {
		this.maAB = maAB;
	}
	public String getImgUrl() {
		return imgUrl;
	}
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}


}
