package com.estore.entity;

// default package
// Generated Aug 23, 2020 8:16:43 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LienHe generated by hbm2java
 */
@Entity
@Table(name = "LienHe")
public class LienHe implements Serializable {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	Integer maLienHe;
	String hoTen;
	String email;
	String chuDe;
	String noiDung;
	public Integer getMaLienHe() {
		return maLienHe;
	}
	public void setMaLienHe(Integer maLienHe) {
		this.maLienHe = maLienHe;
	}
	public String getHoTen() {
		return hoTen;
	}
	public void setHoTen(String hoTen) {
		this.hoTen = hoTen;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getChuDe() {
		return chuDe;
	}
	public void setChuDe(String chuDe) {
		this.chuDe = chuDe;
	}
	public String getNoiDung() {
		return noiDung;
	}
	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}
}
