package com.estore.entity;

// default package
// Generated Aug 23, 2020 8:16:43 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name = "SanPham")
public class SanPham implements Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	int maSanPham;
	String tenSanPham;
	Double giaGoc;
	Double khuyenMai;
	String donViTinh;
	String imgUrl;
	String motaNgan;
	String motaChiTiet;
	Double luotXem;
	int soLuong;

	@ManyToOne
	@JoinColumn(name = "maDanhMuc")
	DanhMucSanPham danhMucSanPham;

	@OneToMany(mappedBy = "sanPham", fetch = FetchType.EAGER)
	List<DonHangChiTiet> donHangChiTiets;

	public int getMaSanPham() {
		return maSanPham;
	}

	public void setMaSanPham(int maSanPham) {
		this.maSanPham = maSanPham;
	}

	public Double getLuotXem() {
		return luotXem;
	}

	public void setLuotXem(Double luotXem) {
		this.luotXem = luotXem;
	}

	public String getTenSanPham() {
		return tenSanPham;
	}

	public void setTenSanPham(String tenSanPham) {
		this.tenSanPham = tenSanPham;
	}

	public Double getGiaGoc() {
		return giaGoc;
	}

	public void setGiaGoc(Double giaGoc) {
		this.giaGoc = giaGoc;
	}

	public Double getKhuyenMai() {
		return khuyenMai;
	}

	public void setKhuyenMai(Double khuyenMai) {
		this.khuyenMai = khuyenMai;
	}

	public String getDonViTinh() {
		return donViTinh;
	}

	public void setDonViTinh(String donViTinh) {
		this.donViTinh = donViTinh;
	}

	public String getImgUrl() {
		return imgUrl;
	}

	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	public String getMotaNgan() {
		return motaNgan;
	}

	public void setMotaNgan(String motaNgan) {
		this.motaNgan = motaNgan;
	}

	public String getMotaChiTiet() {
		return motaChiTiet;
	}

	public void setMotaChiTiet(String motaChiTiet) {
		this.motaChiTiet = motaChiTiet;
	}

	public DanhMucSanPham getDanhMucSanPham() {
		return danhMucSanPham;
	}

	public void setDanhMucSanPham(DanhMucSanPham danhMucSanPham) {
		this.danhMucSanPham = danhMucSanPham;
	}

	public List<DonHangChiTiet> getDonHangChiTiets() {
		return donHangChiTiets;
	}

	public void setDonHangChiTiets(List<DonHangChiTiet> donHangChiTiets) {
		this.donHangChiTiets = donHangChiTiets;
	}

	public int getSoLuong() {
		return soLuong;
	}

	public void setSoLuong(int soLuong) {
		this.soLuong = soLuong;
	}
}
