package com.estore.entity;

// default package
// Generated Aug 23, 2020 8:16:43 AM by Hibernate Tools 4.3.1.Final

import java.io.Serializable;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TinTuc generated by hbm2java
 */
@Entity
@Table(name = "TinTuc")
public class TinTuc implements Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	Integer maTinTuc;
	String tieuDe;
	String noiDung;
	public Integer getMaTinTuc() {
		return maTinTuc;
	}
	public void setMaTinTuc(Integer maTinTuc) {
		this.maTinTuc = maTinTuc;
	}
	public String getTieuDe() {
		return tieuDe;
	}
	public void setTieuDe(String tieuDe) {
		this.tieuDe = tieuDe;
	}
	public String getNoiDung() {
		return noiDung;
	}
	public void setNoiDung(String noiDung) {
		this.noiDung = noiDung;
	}
}
